### PR TITLE
fix: remove addCoins, addCoin and Run `pnpm run docs`

### LINKED ISSUE #590: Remove old functions
Remove `addCoin` and `addCoins`, they are no longer in use after #588 changes

### PR DESCRIPTION
**Pull request by QuinnLee**
## TLDR

Removed `addCoins` and `addCoin` and `pnpm run docs` 

There is a lot of changes on docs

Closes #590

### CODE REVIEW

File: packages/providers/src/transaction-request/transaction-request.ts [hunk 1]
```diff
@@ -315,50 +315,6 @@ abstract class BaseTransactionRequest implements BaseTransactionRequestLike {
     resources.forEach((resource) => this.addResource(resource));
   }
 
-  /**
```
Comment (luizstacio) [inline packages/providers/src/transaction-request/transaction-request.ts:318]: I think we can remove this import from Coin also.

**Review by luizstacio — CHANGES_REQUESTED** [review]

**Review by luizstacio — APPROVED** [review]

**Review by arboleya — APPROVED** [review]
