### PR TITLE
fix: allow setting min gas price in `launchNode` args

### LINKED ISSUE #2813: Make `launchNode` Support Min Gas Price
The [launchNode](https://github.com/FuelLabs/fuels-ts/blob/f3453b9ea669575e3cf97ee50512bc9039845e0c/packages/account/src/test-utils/launchNode.ts#L115) test utility does not support setting the `--min-gas-price` node configuration correctly. 

The issue arises because when the `--min-gas-price` flag is manually specified in the args array, it is not removed from the default flags. As a result, the flag is included twice, leading to an error.

### Intended use:
```ts
  launchNode({
    args: ['--min-gas-price', '0'],
  });
```

### Result Error
```
FuelError: error: the argument '--min-gas-price <MIN_GAS_PRICE>' cannot be used multiple times
```

### PR DESCRIPTION
**Pull request by mvares**
- Closes #2813 

# Summary
In the previous solution, the `minGasPrice` was already defined by default. This PR fixes it by basing it on the `params`.
# Checklist

- [x] I **_added_** — `tests` to prove my changes
- [ ] I **_updated_** — all the necessary `docs`
- [ ] I **_reviewed_** — the entire PR myself, using the GitHub UI
- [ ] I **_described_** — all breaking changes and the Migration Guide

### CODE REVIEW

**Review by petertonysmith94 — APPROVED** [review]

File: packages/account/src/test-utils/launchNode.ts
Comment (petertonysmith94) [inline packages/account/src/test-utils/launchNode.ts:1]: Could we exclude `--min-gas-price` and `--native-executor-version` from the [`remainingArgs`](https://github.com/FuelLabs/fuels-ts/pull/2814/files#diff-b8f07cac51692505e88e065262fd373293a373ed5f6196eb13ec811e37aee136R131)?

Comment (mvares) [reply packages/account/src/test-utils/launchNode.ts:1]: cc @Torres-ssf

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
@mvares Thanks for this contribution 👍  

We are almost there, we only need to remove the `--min-gas-price` from the informed args. 

This is required based on your solution, otherwise the `--min-gas-price` will still be used twice.

You simply need to edit the call to `extractRemainingArgs` at the `launchNode` function.

```ts
    const remainingArgs = extractRemainingArgs(args, [
      '--snapshot',
      '--consensus-key',
      '--db-type',
      '--poa-instant',
      '--min-gas-price', // <- needs to be added here
      '--native-executor-version', // Please can you also add this missing flag?
    ]);
```

File: packages/account/src/test-utils/launchNode.ts
Comment (mvares) [reply packages/account/src/test-utils/launchNode.ts:1]: https://github.com/FuelLabs/fuels-ts/pull/2814/commits/1a22d73cf018c8650a61f0a78fc694d1bab57702

**Comment by mvares** [comment]
Sorry. I still need to edit something.

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
@mvares It would be good if we could also add a test to validate the changes made here.

Let's unskip and change this test case [here](https://github.com/FuelLabs/fuels-ts/blob/f3453b9ea669575e3cf97ee50512bc9039845e0c/packages/account/src/providers/provider.test.ts#L1076-L1090) to:

```ts
  it('should ensure estimated fee values on getTransactionCost are never 0', async () => {
    using launched = await setupTestProviderAndWallets({
      nodeOptions: {
        args: ['--min-gas-price', '0'],
      },
    });
    const { provider } = launched;
    const request = new ScriptTransactionRequest();

    const { minFee, maxFee, gasPrice } = await provider.getTransactionCost(request);

    expect(gasPrice.eq(0)).toBeTruthy();

    expect(maxFee.eq(0)).not.toBeTruthy();
    expect(minFee.eq(0)).not.toBeTruthy();
  });
```

**Comment by mvares** [comment]
:shipit:

File: .changeset/mighty-crews-vanish.md [hunk 1]
```diff
@@ -0,0 +1,4 @@
+---
+---
+
+fix: support minimum gas price in args
```
Comment (Torres-ssf) [inline .changeset/mighty-crews-vanish.md:4]: fix: allow setting min gas price in `launchNode` args

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
@mvares This is the last one

File: .changeset/mighty-crews-vanish.md (hunk 1 above)
Comment (mvares) [reply .changeset/mighty-crews-vanish.md]: https://github.com/FuelLabs/fuels-ts/pull/2814/commits/81eafa3c89827cfa498b0a93404d350ed1bbdf00

**Review by Torres-ssf — APPROVED** [review]

**Review by arboleya — APPROVED** [review]

**Review by nedsalk — APPROVED** [review]
