### PR TITLE
docs: fix code in context links

### LINKED ISSUE #1024: Some links to code snippets are broken in our docs
If you click on 'See code in context' for any of the code snippets on https://fuellabs.github.io/fuels-ts/guide/contracts/inter-contract-calls.html, you will notice that the links are broken. eg. `https://github.com/FuelLabs/fuels-ts/blob/master/undefined#L1-L25`

### PR DESCRIPTION
**Pull request by Torres-ssf**
- Close #1024

### CODE REVIEW

File: apps/docs/.vitepress/plugins/snippetPlugin.ts [hunk 1]
```diff
@@ -119,7 +119,12 @@ export const snippetPlugin = (md: MarkdownIt, srcDir: string) => {
           .join('\n')
       );
 
-      const [, partialPath] = filepath.split(/(packages\/.*)/);
+      const match = filepath.match(/(packages|apps)\/(.*)/);
+      const partialPath = match ? match[0] : '';
```
Comment (arboleya) [inline apps/docs/.vitepress/plugins/snippetPlugin.ts:123]: Maybe this would suffice.

```suggestion
      const partialPath = match?.[0];
```

**Review by arboleya — APPROVED** [review]

**Review by danielbate — APPROVED** [review]

**Review by danielbate — APPROVED** [review]
