### PR TITLE
fix: proxy contract versions not being updated correctly

### LINKED ISSUE #3338: Release PR doesn't update proxy contract versions correctly
[This](https://github.com/FuelLabs/fuels-ts/commit/9ebd6c224482a9b3c409409e9f0e14cb0de38224#diff-e2d17058cfc056bd4d8a6c9d395b7d7112f90eefb72d77fd845c56b137f054adR8) should have been an update from `0.96.0` to `0.96.1`, but it's an update from `0.95.0` to `0.96.0`. https://github.com/FuelLabs/fuels-ts/pull/3221 should've fixed this but it's still not working.

### PR DESCRIPTION
**Pull request by nedsalk**
- Closes #3338 

# Summary

The `prebuild` script wasn't building the `versions` package so `fuels-typegen` would pick up the _old_ version of `fuels`, not the one that'll be released with the release PR.

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

**Review by danielbate — DISMISSED** [review]

**Review by Torres-ssf — DISMISSED** [review]

File: scripts/changeset/changeset-version-with-docs.ts [hunk 1]
```diff
@@ -16,8 +16,13 @@ import { error } from 'console';
      */
     execSync(`changeset version`);
 
-    // Invoke versions' prebuild script (will rewrite version files if needed)
-    execSync(`pnpm -C packages/versions prebuild`);
+    /**
+     * Invoke versions' build script (will rewrite version files if needed)
+     * and build the versions package,
+     * so that fuels-typegen picks up the new fuels version
+     * when generating the proxy contract below.
```
Comment (arboleya) [inline scripts/changeset/changeset-version-with-docs.ts:23]: Just equalizing the line breaks.

```suggestion
     * Invoke versions' build script (will rewrite version files if needed)
     * and build the versions package, so that fuels-typegen picks up the
     * new fuels version when generating the proxy contract below.
```

**Review by arboleya — DISMISSED** [review]

**Review by danielbate — APPROVED** [review]

**Review by Torres-ssf — APPROVED** [review]

**Review by arboleya — APPROVED** [review]

**Review by Dhaiwat10 — APPROVED** [review]
