### PR TITLE
chore: fix deprecation on Commander method

### LINKED ISSUE #3207: Fix deprecation on Commander method
>_Originally posted by @maschad in https://github.com/FuelLabs/fuels-ts/pull/3190#discussion_r1774065680_
            

_Not directly related to this PR, but there's another instance of this [here](https://github.com/FuelLabs/fuels-ts/blob/aa/feat/support-deploying-proxy-contracts/packages/create-fuels/src/lib/setupProgram.ts#L31)._

### PR DESCRIPTION
**Pull request by Dhaiwat10**
> Closes TS-662
- Closes #3207 

# Summary

This PR removes the usage of the `addHelpCommand` method from the `commander` package that we use for our CLIs. We don't need to replace it with anything since `commander` now automatically adds a help command for your CLI if it has any sub-commands, which our CLIs do.

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

File: packages/fuels/src/cli.ts [hunk 1]
```diff
@@ -32,7 +32,6 @@ export const configureCli = () => {
 
   program.version(versions.FUELS, '-v, --version', 'Output the version number');
   program.helpOption('-h, --help', 'Display help');
-  program.addHelpCommand('help [command]', 'Display help for command');
```
Comment (arboleya) [inline packages/fuels/src/cli.ts:35]: No need to remove this here, as this will be handled via:
 - https://github.com/FuelLabs/fuels-ts/pull/3190

**Review by arboleya — CHANGES_REQUESTED** [review]

File: packages/fuels/src/cli.ts (hunk 1 above)
Comment (Dhaiwat10) [reply packages/fuels/src/cli.ts:35]: Cool, I've just changed it to use `helpCommand` instead of `addHelpCommand` for now

Comment (Dhaiwat10) [reply packages/fuels/src/cli.ts:35]: https://github.com/FuelLabs/fuels-ts/pull/3210/commits/3f10f1f88d6d6ef5a29ec891a801ad4598aa35ef

**Review by maschad — APPROVED** [review]

**Review by Torres-ssf — APPROVED** [review]

**Review by arboleya — APPROVED** [review]
